#!/usr/bin/env bash
set -Eeuo pipefail

AGENT_ENV=/etc/ssh-store-agent/agent.env
[[ -r "$AGENT_ENV" ]] && . "$AGENT_ENV"
AGENT_PORT="${AGENT_PORT:-8787}"
AGENT_SECRET="${AGENT_SHARED_SECRET:-}"
ADMIN_PANEL_URL="${ADMIN_PANEL_URL:-https://www.domain-anda.com/admin}"
OS_NAME="$(. /etc/os-release 2>/dev/null && printf '%s %s' "${NAME:-Linux}" "${VERSION_ID:-}" || printf 'Linux')"
if [[ -x /usr/local/sbin/ssh-store-license-check ]] && ! /usr/local/sbin/ssh-store-license-check >/dev/null 2>&1; then clear 2>/dev/null || true; printf "\033[31mSCRIPT PREMIUM TIDAK AKTIF\033[0m\n"; printf "Masa trial/lisensi berakhir. Hubungi admin untuk memperpanjang.\n"; exit 1; fi

ESC=$'\033'
RESET="${ESC}[0m"; CYAN="${ESC}[36m"; BLUE="${ESC}[34m"; GREEN="${ESC}[32m"; YELLOW="${ESC}[33m"; RED="${ESC}[31m"; MAGENTA="${ESC}[35m"; DIM="${ESC}[2m"
clear_screen(){ command -v clear >/dev/null 2>&1 && clear || true; printf '\033[2J\033[H'; }
item(){ local text="$1"; printf '  %s\n' "$text"; }
line(){ local width; width=$(tput cols 2>/dev/null || echo 60); (( width > 60 )) && width=60; printf '%b\n' "${CYAN}$(printf '%*s' "$width" '' | tr ' ' '-')${RESET}"; }
logo(){ printf "%b\n" "${CYAN}██╗  ██╗  █████╗  ██████╗ ██╗██████╗ ${RESET}"; printf "%b\n" "${BLUE}██║  ██║ ██╔══██╗██╔══██╗██║██╔══██╗${RESET}"; printf "%b\n" "${MAGENTA}███████║ ███████║██████╔╝██║██████╔╝${RESET}"; printf "%b\n" "${YELLOW}██╔══██║ ██╔══██║██╔══██╗██║██╔══██╗${RESET}"; printf "%b\n" "${GREEN}██║  ██║ ██║  ██║██████╔╝██║██████╔╝${RESET}"; }
header(){ clear_screen; logo; printf "%b\n" "${DIM}Script khusus website SSH Store${RESET}"; printf "%b\n" "${YELLOW}SCRIPT INI PREMIUM BERLANGGANAN${RESET}"; printf "%b\n" "${YELLOW}SCRIPT INI HANYA AKTIF 3 HARI TRIAL. JIKA PELANGGAN TIDAK MEMPERPANJANG, SCRIPT TIDAK DAPAT DIJALANKAN.${RESET}"; printf "%b\n" "${BLUE}Hubungi: 081374452477 untuk berlangganan script premium${RESET}"; printf "%b\n" "${DIM}VPS Provisioning & Tunnel Control Panel${RESET}"; printf "%b\n" "${BLUE}OS VPS: ${OS_NAME}${RESET}"; printf "%b\n" "${BLUE}Panel Admin: ${ADMIN_PANEL_URL}${RESET}"; line; printf "%b\n" "${GREEN}  Status: SIAP DIGUNAKAN${RESET}"; line; }
request(){ local method="$1" path="$2" body="${3:-{}}"; local ts sig; ts="$(date +%s)"; sig="$(printf '%s.%s' "$ts" "$body" | openssl dgst -sha256 -hmac "$AGENT_SECRET" -hex | sed 's/^.* //')"; curl --fail-with-body -sS --max-time 12 -X "$method" "http://127.0.0.1:${AGENT_PORT}${path}" -H "content-type: application/json" -H "x-agent-timestamp: ${ts}" -H "x-agent-signature: ${sig}" -d "$body"; }
pretty(){ if command -v python3 >/dev/null 2>&1; then python3 -m json.tool 2>/dev/null || cat; else cat; fi; }
list_accounts(){ echo; printf '%b\n' "${CYAN}DAFTAR AKUN SSH${RESET}"; if [[ -f /var/lib/ssh-store-agent/accounts.json ]]; then cat /var/lib/ssh-store-agent/accounts.json | pretty; else echo 'Belum ada akun.'; fi; read -r -p 'Tekan Enter untuk kembali...' _; }
create_account(){ local username days body result; read -r -p 'Username baru: ' username; read -r -p 'Masa aktif (hari): ' days; if [[ ! "$username" =~ ^[a-z][a-z0-9_-]{2,31}$ ]]; then printf '%b\n' "${RED}Username harus 3-32 karakter, diawali huruf kecil, tanpa spasi.${RESET}"; read -r -p 'Tekan Enter...' _; return; fi; if [[ ! "$days" =~ ^[0-9]+$ ]] || (( days < 1 || days > 365 )); then printf '%b\n' "${RED}Masa aktif harus angka 1 sampai 365 hari.${RESET}"; read -r -p 'Tekan Enter...' _; return; fi; printf -v body '{"username":"%s","days":%s}' "$username" "$days"; result="$(request POST /accounts "$body" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Akun berhasil dibuat:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
extend_account(){ local username days body result; read -r -p 'Username: ' username; read -r -p 'Tambah masa aktif (hari): ' days; if [[ ! "$username" =~ ^[a-z][a-z0-9_-]{2,31}$ ]] || [[ ! "$days" =~ ^[0-9]+$ ]] || (( days < 1 || days > 365 )); then printf '%b\n' "${RED}Username atau masa aktif tidak valid. Hari harus 1 sampai 365.${RESET}"; read -r -p 'Tekan Enter...' _; return; fi; printf -v body '{"username":"%s","days":%s}' "$username" "$days"; result="$(request POST /accounts/extend "$body" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Masa aktif diperbarui:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
status_account(){ local username status result; read -r -p 'Username: ' username; read -r -p 'Status (active/suspended): ' status; result="$(request POST /accounts/status "{\"username\":\"${username}\",\"status\":\"${status}\"}" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Status diperbarui:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
delete_account(){ local username confirm result; read -r -p 'Username yang dihapus: ' username; read -r -p "Ketik HAPUS untuk konfirmasi ${username}: " confirm; [[ "$confirm" == 'HAPUS' ]] || { echo 'Dibatalkan.'; sleep 1; return; }; result="$(request DELETE "/accounts/${username}" '{}' 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Akun dihapus:${RESET} ${result}"; read -r -p 'Tekan Enter...' _; }
account_menu(){ while true; do header; printf '%b\n' "${YELLOW}  PILIHAN SSH / WEBSOCKET${RESET}"; item '1. Lihat daftar akun'; item '2. Buat akun baru'; item '3. Perpanjang akun'; item '4. Suspend / aktifkan akun'; item '5. Hapus akun'; item '0. Kembali'; line; read -r -p '  Pilih menu: ' choice; case "$choice" in 1) list_accounts;;2) create_account;;3) extend_account;;4) status_account;;5) delete_account;;0) return;;*) echo 'Pilihan tidak tersedia.'; sleep 1;; esac; done; }
protocol_menu(){ while true; do header; printf '%b\n' "${YELLOW}  MENU LAYANAN WEBSITE${RESET}"; item '1. SSH WebSocket'; item '2. OpenVPN WebSocket'; item '3. V2Ray / VLESS'; item '4. Trojan'; item '5. Shadowsocks'; item '6. WireGuard'; item '7. WebSocket SSL / TLS'; item '0. Keluar / Logout'; line; read -r -p '  Ketik nomor protocol: ' choice; case "$choice" in 1) account_menu;;2|3|4|5|6|7) echo; printf '%b\n' "${YELLOW}Protocol dipilih: ${choice}.${RESET}"; echo 'Menu layanan ini siap dikonfigurasi dari panel admin website.'; read -r -p 'Tekan Enter untuk kembali...' _;;0) clear_screen; exit 0;;*) echo 'Pilihan tidak tersedia.'; sleep 1;; esac; done; }
protocol_menu
