#!/usr/bin/env bash
set -Eeuo pipefail

AGENT_ENV=/etc/ssh-store-agent/agent.env
[[ -r "$AGENT_ENV" ]] && . "$AGENT_ENV"
AGENT_PORT="${AGENT_PORT:-8787}"
AGENT_SECRET="${AGENT_SHARED_SECRET:-}"

ESC=$'\033'
RESET="${ESC}[0m"; CYAN="${ESC}[36m"; BLUE="${ESC}[34m"; GREEN="${ESC}[32m"; YELLOW="${ESC}[33m"; RED="${ESC}[31m"; MAGENTA="${ESC}[35m"; DIM="${ESC}[2m"
clear_screen(){ printf '\033c'; }
line(){ printf '%b\n' "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"; }
logo(){ printf "%b\n" "${CYAN}██╗  ██╗ █████╗ ██████╗ ██╗██████╗ ██╗██╗     ██╗      █████╗ ██╗  ██╗${RESET}"; printf "%b\n" "${BLUE}██║  ██║██╔══██╗██╔══██╗██║██╔══██╗██║██║     ██║     ██╔══██╗██║  ██║${RESET}"; printf "%b\n" "${MAGENTA}███████║███████║██████╔╝██║██████╔╝██║██║     ██║     ███████║███████║${RESET}"; printf "%b\n" "${YELLOW}██╔══██║██╔══██║██╔══██╗██║██╔══██╗██║██║     ██║     ██╔══██║██╔══██║${RESET}"; printf "%b\n" "${GREEN}██║  ██║██║  ██║██████╔╝██║██████╔╝██║███████╗███████╗██║  ██║██║  ██║${RESET}"; printf "%b\n" "${RED}╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝╚═════╝ ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝${RESET}"; }
header(){ clear_screen; logo; printf "%b\n" "${DIM}Script khusus website SSH Store${RESET}"; printf "%b\n" "${DIM}VPS Provisioning & Tunnel Control Panel${RESET}"; line; printf "%b\n" "${GREEN}  Status: SIAP DIGUNAKAN${RESET}"; line; }
request(){ local method="$1" path="$2" body="${3:-{}}"; local ts sig; ts="$(date +%s)"; sig="$(printf '%s.%s' "$ts" "$body" | openssl dgst -sha256 -hmac "$AGENT_SECRET" -hex | sed 's/^.* //')"; curl -fsS --max-time 12 -X "$method" "http://127.0.0.1:${AGENT_PORT}${path}" -H "content-type: application/json" -H "x-agent-timestamp: ${ts}" -H "x-agent-signature: ${sig}" -d "$body"; }
pretty(){ if command -v python3 >/dev/null 2>&1; then python3 -m json.tool 2>/dev/null || cat; else cat; fi; }
list_accounts(){ echo; printf '%b\n' "${CYAN}DAFTAR AKUN SSH${RESET}"; if [[ -f /var/lib/ssh-store-agent/accounts.json ]]; then cat /var/lib/ssh-store-agent/accounts.json | pretty; else echo 'Belum ada akun.'; fi; read -r -p 'Tekan Enter untuk kembali...' _; }
create_account(){ local username days result; read -r -p 'Username baru: ' username; read -r -p 'Masa aktif (hari): ' days; result="$(request POST /accounts "{\"username\":\"${username}\",\"days\":${days}}" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Akun berhasil dibuat:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
extend_account(){ local username days result; read -r -p 'Username: ' username; read -r -p 'Tambah masa aktif (hari): ' days; result="$(request POST /accounts/extend "{\"username\":\"${username}\",\"days\":${days}}" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Masa aktif diperbarui:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
status_account(){ local username status result; read -r -p 'Username: ' username; read -r -p 'Status (active/suspended): ' status; result="$(request POST /accounts/status "{\"username\":\"${username}\",\"status\":\"${status}\"}" 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Status diperbarui:${RESET}"; printf '%s\n' "$result" | pretty; read -r -p 'Tekan Enter...' _; }
delete_account(){ local username confirm result; read -r -p 'Username yang dihapus: ' username; read -r -p "Ketik HAPUS untuk konfirmasi ${username}: " confirm; [[ "$confirm" == 'HAPUS' ]] || { echo 'Dibatalkan.'; sleep 1; return; }; result="$(request DELETE "/accounts/${username}" '{}' 2>&1)" || { printf '%b\n' "${RED}Gagal: ${result}${RESET}"; read -r -p 'Tekan Enter...' _; return; }; printf '%b\n' "${GREEN}Akun dihapus:${RESET} ${result}"; read -r -p 'Tekan Enter...' _; }
account_menu(){ while true; do header; printf '%b\n' "${YELLOW}  PILIHAN SSH / WEBSOCKET${RESET}"; printf '%b\n' '  1. Lihat daftar akun'; printf '%b\n' '  2. Buat akun baru'; printf '%b\n' '  3. Perpanjang akun'; printf '%b\n' '  4. Suspend / aktifkan akun'; printf '%b\n' '  5. Hapus akun'; printf '%b\n' '  0. Kembali'; line; read -r -p '  Pilih menu: ' choice; case "$choice" in 1) list_accounts;;2) create_account;;3) extend_account;;4) status_account;;5) delete_account;;0) return;;*) echo 'Pilihan tidak tersedia.'; sleep 1;; esac; done; }
protocol_menu(){ while true; do header; printf '%b\n' "${YELLOW}  MENU LAYANAN WEBSITE${RESET}"; printf '%b\n' '  1. SSH WebSocket'; printf '%b\n' '  2. OpenVPN WebSocket'; printf '%b\n' '  3. V2Ray / VLESS'; printf '%b\n' '  4. Trojan'; printf '%b\n' '  5. Shadowsocks'; printf '%b\n' '  6. WireGuard'; printf '%b\n' '  7. WebSocket SSL / TLS'; printf '%b\n' '  0. Keluar / Logout'; line; read -r -p '  Ketik nomor protocol: ' choice; case "$choice" in 1) account_menu;;2|3|4|5|6|7) echo; printf '%b\n' "${YELLOW}Protocol dipilih: ${choice}.${RESET}"; echo 'Menu layanan ini siap dikonfigurasi dari panel admin website.'; read -r -p 'Tekan Enter untuk kembali...' _;;0) clear_screen; exit 0;;*) echo 'Pilihan tidak tersedia.'; sleep 1;; esac; done; }
protocol_menu
